participant = [
  "Sylvain",
  "Gabriel",
  "Tomy",
  "Laurent",
  "Vincent",
  "Dave",
  "Jean-Bernard",
  "Alexandre",
];

var positionGPS = new Array();
positionGPS[0] = new Array(0, 0);
positionGPS[1] = new Array(0, 0);
positionGPS[2] = new Array(0, 0);
positionGPS[3] = new Array(0, 0);
positionGPS[4] = new Array(0, 0);
positionGPS[5] = new Array(0, 0);
positionGPS[6] = new Array(0, 0);
positionGPS[7] = new Array(0, 0);
positionGPS[8] = new Array(0, 0);
positionGPS[9] = new Array(0, 0);

function initialiserEquipe() {
  //College d'Alma
  positionGPS[0][0] = 48.545389;
  positionGPS[0][1] = -71.654857;
  //UQAC
  positionGPS[1][0] = 48.419172;
  positionGPS[1][1] = -71.052653;
  //Galerie de la Capitale
  positionGPS[2][0] = 46.831086;
  positionGPS[2][1] = -71.299388;
  //Centre Bell
  positionGPS[3][0] = 45.49618;
  positionGPS[3][1] = -73.569278;
  //Parlement d'Ottawa
  positionGPS[4][0] = 45.425198;
  positionGPS[4][1] = -75.699824;
  //tour Eiffel
  positionGPS[5][0] = 48.858547;
  positionGPS[5][1] = 2.294481;
  //
  positionGPS[6][0] = 48.3651200676972;
  positionGPS[6][1] = -69.45603283662265;

  positionGPS[7][0] = 48.601927829763525;
  positionGPS[7][1] = -72.34082224959018;
  //
  positionGPS[8][0] = 48.89193368592226;
  positionGPS[8][1] = -72.23448339615906;

  positionGPS[9][0] = 49.27810054342625;
  positionGPS[9][1] = -123.1548049282394;
}
